--CREATE DATABASE MARKET
--USE MARKET

-- VEZIFE CEDVELI

--CREATE TABLE VEZIFE(
--ID INT PRIMARY KEY IDENTITY,
--VEZIFE NVARCHAR(50)
--)

SELECT * FROM VEZIFE

--ISHCI CEDVELI

--CREATE TABLE ISHCI(
--ID INT PRIMARY KEY IDENTITY,
--MKOD INT,
--VEZIFEID INT REFERENCES VEZIFE(ID),
--MAASH FLOAT
--)

SELECT * FROM ISHCI


-- FILIAL CEDVELI 

--CREATE TABLE FILIAL(
--ID INT PRIMARY KEY IDENTITY,
--FILIAL NVARCHAR(50)
--)

SELECT * FROM FILIAL

-- MEHSUL CEDVELI

--CREATE TABLE MEHSUL(
--ID INT PRIMARY KEY IDENTITY,
--AD NVARCHAR(50),
--ALISHQIYMETI FLOAT,
--SATISHQIYMETI FLOAT
--)

SELECT * FROM MEHSUL


-- SATISH CEDVELI

--CREATE TABLE SATISH(
--ID INT PRIMARY KEY IDENTITY,
--MEHSULID INT REFERENCES MEHSUL(ID),
--ISHCIID INT REFERENCES ISHCI(ID),
--ENDIRIM FLOAT,
--SATISHTARIXI DATE
--)


SELECT * FROM SATISH

-- 2.BUTUN SATISHLARIN CEMINI TAP
--SELECT COUNT(*) AS SATISHLAR FROM SATISH

-- 3.CARI AYDA MEHSULLARIN SATISINDAN GELEN YEKUN MEBLEGI TAP

--SELECT 
--(SELECT(SATISHQIYMETI) FROM MEHSUL WHERE ID=1) * (SELECT COUNT(*) AS ALMA FROM SATISH WHERE MEHSULID=1) +
--(SELECT(SATISHQIYMETI) FROM MEHSUL WHERE ID=2) * (SELECT COUNT(*) AS QOZ FROM SATISH WHERE MEHSULID=2) +
--(SELECT(SATISHQIYMETI) FROM MEHSUL WHERE ID=3) * (SELECT COUNT(*) AS QARPIZ FROM SATISH WHERE MEHSULID=3)
--AS YEKUNMEBLEG 


-- 5.CARI AYDA HER ISHCININ SATDIGI MEHSULLARIN SAYINI TAP

--SELECT COUNT(*) FROM SATISH WHERE ISHCIID=1
--SELECT COUNT(*) FROM SATISH WHERE ISHCIID=2
--SELECT COUNT(*) FROM SATISH WHERE ISHCIID=3

-- 6.CARI AYDA HER ISHCININ SATDIGI MEHSULLARIN YEKUN ODENISINI TAP

--SELECT TOP 1 
--(SELECT(SATISHQIYMETI) FROM MEHSUL WHERE ID=1) * (SELECT COUNT(*) AS ALMA FROM SATISH WHERE MEHSULID=1 AND ISHCIID=2) +
--(SELECT(SATISHQIYMETI) FROM MEHSUL WHERE ID=2) * (SELECT COUNT(*) AS QOZ FROM SATISH WHERE MEHSULID=2 AND ISHCIID=2) +
--(SELECT(SATISHQIYMETI) FROM MEHSUL WHERE ID=3) * (SELECT COUNT(*) AS QARPIZ FROM SATISH WHERE MEHSULID=3 AND ISHCIID=2)
--AS ISHCI FROM SATISH 

--SELECT TOP 1
--(SELECT(SATISHQIYMETI) FROM MEHSUL WHERE ID=1) * (SELECT COUNT(*) AS ALMA FROM SATISH WHERE MEHSULID=1 AND ISHCIID=4) +
--(SELECT(SATISHQIYMETI) FROM MEHSUL WHERE ID=2) * (SELECT COUNT(*) AS QOZ FROM SATISH WHERE MEHSULID=2 AND ISHCIID=4) +
--(SELECT(SATISHQIYMETI) FROM MEHSUL WHERE ID=3) * (SELECT COUNT(*) AS QARPIZ FROM SATISH WHERE MEHSULID=3 AND ISHCIID=4)
--AS SENIORISHCI FROM SATISH

-- 7.CARI AYDA HER ISHCININ SATDIGI MEHSULLARDAN QALAN XEYRI TAP

--SELECT 
--(SELECT(SATISHQIYMETI - ALISHQIYMETI) FROM MEHSUL WHERE ID=1) * (SELECT COUNT(*) AS ALMA FROM SATISH WHERE MEHSULID=1 AND ISHCIID=2) +
--(SELECT(SATISHQIYMETI - ALISHQIYMETI) FROM MEHSUL WHERE ID=2) * (SELECT COUNT(*) AS QOZ FROM SATISH WHERE MEHSULID=2 AND ISHCIID=2) +
--(SELECT(SATISHQIYMETI - ALISHQIYMETI) FROM MEHSUL WHERE ID=3) * (SELECT COUNT(*) AS QARPIZ FROM SATISH WHERE MEHSULID=3 AND ISHCIID=2)
--AS ISHCIXEYIR 

--SELECT 
--(SELECT(SATISHQIYMETI - ALISHQIYMETI) FROM MEHSUL WHERE ID=1) * (SELECT COUNT(*) AS ALMA FROM SATISH WHERE MEHSULID=1 AND ISHCIID=4) +
--(SELECT(SATISHQIYMETI - ALISHQIYMETI) FROM MEHSUL WHERE ID=2) * (SELECT COUNT(*) AS QOZ FROM SATISH WHERE MEHSULID=2 AND ISHCIID=4) +
--(SELECT(SATISHQIYMETI - ALISHQIYMETI) FROM MEHSUL WHERE ID=3) * (SELECT COUNT(*) AS QARPIZ FROM SATISH WHERE MEHSULID=3 AND ISHCIID=4)
--AS SENIORISHCIXEYIR

-- 9.CARI AYDA HER MEHSULDAN NECE EDED SATILDIGINI TAP

--SELECT COUNT(*) AS ALMA FROM SATISH WHERE MEHSULID=1
--SELECT COUNT(*) AS QOZ FROM SATISH WHERE MEHSULID=2
--SELECT COUNT(*) AS QARPIZ FROM SATISH WHERE MEHSULID=3

-- 10. CARI AYDA EN COX SATILAN MEHSULU TAP

--SELECT TOP 1 MEHSULID,
--COUNT(MEHSULID) AS SATISHSAYI
--FROM SATISH
--GROUP BY(MEHSULID)
--ORDER BY SATISHSAYI DESC

